#!/usr/bin/env python
import click
import functools
import robostat.db
import robostat.web.db
from robostat import cli

db = None

echo = functools.partial(click.secho, err=True)

@click.group()
@click.option("-v", "--verbose", count=True)
@click.option("-d", "--db", type=cli.SQLAParamType(session_args={"expire_on_commit":False}),
        envvar="ROBOSTAT_DB", required=True)
@click.option("-i", "--init", envvar="ROBOSTAT_INIT")
def rsman(**kwargs):
    global db
    db = kwargs["db"]

    if kwargs["init"]:
        exec(open(kwargs["init"]).read())

@rsman.command()
def create():
    echo("Creating new database in %s" % db.engine.url)
    robostat.db.Base.metadata.create_all(db.engine)

if __name__ == "__main__":
    rsman()
